services:
  # CricketService API container
  cricketservice-api:
    build:
      context: .
      dockerfile: CricketService.Api/Dockerfile
    container_name: cricketservice-api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresServer__ConnectionString=Host=cricket-service-database;Port=5432;Username=postgres;Password=admin;Database=cricket_database
      - Hangfire__DatabaseConnectionString=Host=hangfire-database;Port=5432;Username=postgres;Password=admin;Database=hangfire
    depends_on:
      - cricket-service-database
      - hangfire-database

  # new db container on port 5440
  cricket-service-database:
    image: postgres:latest
    container_name: cricket-info-service-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5440:5432"  # Maps host port 5440 to container port 5432
    volumes:
      - cricket-info-service-db:/var/lib/postgresql
    restart: unless-stopped

  # hangfire db container on port 5441
  hangfire-database:
    image: postgres:latest
    container_name: hangfire-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${HANGFIRE_USER}
      POSTGRES_PASSWORD: ${HANGFIRE_PASSWORD}
      POSTGRES_DB: ${HANGFIRE_DB}
    ports:
      - "5441:5432"  # Maps host port 5441 to container port 5432
    volumes:
      - hangfire-db:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
  cricket-info-service-db:
  hangfire-db: